# Generated by Django 2.2.6 on 2019-11-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobnum',
            new_name='mo_num',
        ),
    ]
